// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCommerce.UIX.Models;

public partial class Product
{
    public string Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool Enabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Picture { get; set; }
}