// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCommerce.UIX.Models;

public partial class User
{
    public string Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string DisplayName { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual UserRole Role { get; set; }
}